apiVersion: v1
baseDomain: lab01.one
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 2
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 1
metadata:
  creationTimestamp: null
  name: ocp-east
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  vsphere:
    apiVIP: 172.16.10.251
    cluster: cmp
    datacenter: lab01
    defaultDatastore: vsanDatastore
    ingressVIP: 172.16.10.252
    network: pg-mgmt
    password: VMware1!SDDC
    username: administrator@vsphere.local
    vCenter: vcenter.lab01.one
publish: External
pullSecret: ''
sshKey: |
  
